### ISSUE TITLE
JB2A patreon?

### ISSUE THREAD

**Issue by ctbritt** [boss-loot/Boss-Loot-Interactive-Magic-Items#2]
hi! this looks amazing, but could you include a dependency on either JB2A _DnD5e or JB2A_patreon for those of us who support JB2A, please?

**Comment by boss-loot** [comment]
Thanks for your suggestion. I'll start looking on how to integrate the module with J2BA.

**Comment by ravingdragoon** [comment]
I am having the same issue. It looks like other modules are requiring [automated-jb2a-animations](https://github.com/otigon/automated-jb2a-animations) instead, and letting that handle the determination of free or patreon version of jb2a.

**Comment by ravingdragoon** [comment]
After the 0.0.9 update the module is still force installing the free version of jb2a, at least on The Forge, as a dependency.

**Comment by boss-loot** [comment]
You should simply ignore the message and close the pop-up window that request to install the free version of the JB2A.

**Comment by ravingdragoon** [comment]
In The Forge you don't get a choice, it just auto-installs anything listed as a dependency.

**Comment by ravingdragoon** [comment]
I did find a somewhat annoying but seemingly functional work around. After it installs I can go in to my world data  files and manually delete the free version. For some reason it won't let me uninstall it from the Bazaar, it says it requires a delete code, which can only be entered by deleting from the world data files.

**Comment by quantiq** [comment]
The module is updated and compatible with j2ba Patreon. Some issues remains with the Portal Daggers we will update tomorow. A work around is to have both jb2a Free and Patreon installed.

**Comment by boss-loot** [comment]
Solved in v0.0.10
Support for JB2A_DnD5e and/or jb2a_patreon
It is mandatory to have at least one of JB2A_DnD5e or jb2a_patreon.
If one have only jb2a_patreon installed just close the pop-up that inform you to install JB2A_DnD5e.

**Comment by Gacky2k** [comment]
I have all the dependencies installed, but in game, when I try to activate Boss Loot, it is still greyed out and tells me I don't have all the dependencies installed.

**Comment by boss-loot** [comment]
As this issue it's already closed, I will open a new one and we can continue there.
