### ISSUE TITLE
Cannot activate module

### ISSUE THREAD

**Issue by boss-loot** [boss-loot/Boss-Loot-Interactive-Magic-Items#3]
Users reported:
"I have all the dependencies installed, but in game, when I try to activate Boss Loot, it is still greyed out and tells me I don't have all the dependencies installed."

**Comment by boss-loot** [comment]
I would like to know more details on this issue:
 
1. Do you use foundry on Linux or Windows?
2. What version of Boss Loot do you have installed?
3. Please open the console (press f12 from your browser) and let me know if you see some errors or warnings
4. Try restart foundry and see if this helps.

**Comment by Gacky2k** [comment]
1.  Windows
2.  Latest version 0.0.11
3.  465 messages, No errors, 18 warnings.  All warnings about midiqol disabling some features with other modules that are not even activated.
4. Nope..didn't help

I have created a blank new world just to test.  ONLY installed the required dependencies that are listed on the main page...I  use them all already anyways.  Refresh Foundry after enabling them...then go into manage modules once more and it's still grey out telling me that dependencies aren't installed.

Next, I enabled the suggested modules too, same issue...didn't help.

Foundry version etc visible in screen shots I've attached.
![Screenshot 2023-04-27 210514](https://user-images.githubusercontent.com/49887457/235030202-5dd3b4b6-aff7-4160-9399-c5681eb0559d.png)
![Screenshot 2023-04-27 210613](https://user-images.githubusercontent.com/49887457/235030211-63c849bb-2835-454e-b535-9a5ff9927144.png)

**Comment by boss-loot** [comment]
Hello,

This is a very strange behavior because Boss Loot is a compendium module, which means that it has no dependencies required to install and activate it. What I mean is that you should be able to activate the module even if the dependencies are not yet installed or activated. The only downside would be that the items will not work as intended.

Could you please try to perform a fresh installation (uninstall and then install again) of the module, and let me know the result?

Best regards.

**Comment by Gacky2k** [comment]
Uninstalled, reinstalled....unfortunately...same issue.  Even tried uninstalling it...exiting Foundry, then reinstalling it and trying to activate it again.  Still greyed out with message about missing dependencies. 

Just getting home from work...here in a bit.  I'll drag out my laptop, do a complete new Foundry install on it w/o anything else module wise downloaded/activated, and try again.

**Comment by Gacky2k** [comment]
Got it working...The best I can tell.  It will ONLY allow me to activate it if the free version of JB2A is installed.  JB2A patreon users such as myself get the full version naturally.  The paid version is "jb2a_patreon" and installs into a folder with that same name.  So, looks like where ever you're looking for JB2A to be installed, and looking for "JB2A_DnD5e" (the free version), will need to also add "jb2a_patreon" to that list...or however you're doing it.

**Comment by boss-loot** [comment]
Thanks for feedback. Just note that you don't need to activate the JB2A_DnD5e module, it should work with the animations from jb2a_patreon just fine.
Either way, in the next release I will remove the dependency for JB2A_DnD5e.

Thanks.

**Comment by boss-loot** [comment]
I just released version 0.0.12, which no longer checks if one have installed JB2A_DnD5e. However, please note that the module still requires either JB2A_DnD5e or jb2a_patreon to function properly. 

Thank you.

**Comment by boss-loot** [comment]
solved in 0.0.12
