### ISSUE TITLE
Module can't find images

### ISSUE THREAD

**Issue by ravingdragoon** [boss-loot/Boss-Loot-Interactive-Magic-Items#4]
Hello,
I am on Windows 10 running Foundry v10.291 with DnD5e v2.1.5 on The Forge in Google Chrome Version 112.0.5615.138 (Official Build) (64-bit). 
Since updating from Boss Loot Interactive Magic Items, Free Pack v0.0.9 to v0.0.10 I am no longer able to see any of the artwork. I get the following errors in the Console:
```
08:21:25.950art-static-portal-dagger-secundus.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.950 art-static-portal-dagger-quartus.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.950 art-static-stormforger-staff.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.951 art-static-helm-of-the-charging-bull.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.951 art-static-destabilizator.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.953 art-static-void-vortex.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.953 art-static-death-kiss-blade.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.954 art-static-portal-dagger-prime.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.977 art-static-portal-dagger-tertius.webp:1     Failed to load resource: the server responded with a status of 404 ()
08:21:25.977 art-static-chainweaver-bracer.webp:1     Failed to load resource: the server responded with a status of 404 ()
```
![image](https://user-images.githubusercontent.com/72875320/234912142-1e1de0df-7245-410d-abb8-19dc70ff14e9.png)

**Comment by boss-loot** [comment]
Hello,
Most likely there was an issue during the update from 0.0.9 to 0.0.10
Can you please uninstall the module and install v0.0.10?

To uninstall the module, open the Foundry app, go to Add-on Modules tab, search for Boss Loot module and clic uninstall:
![image](https://user-images.githubusercontent.com/125301566/234927535-9cdd1bdf-63f8-432c-b3f3-3a2351bf118a.png)

After that just click on Install Module (bottom left button) and search for Boss Loot.

**Comment by ravingdragoon** [comment]
I already tried this, it did not fix the issue. Also, I'm not sure if it makes any difference but the install and uninstall method does not work the same way on The Forge:

![image](https://user-images.githubusercontent.com/72875320/234934083-12830cd8-3f7b-48e5-850d-80d6839ec60b.png)

**Comment by boss-loot** [comment]
After analyzing the issue I found out that there were some issue with the path to artwork. I made a new release 0.0.11 which should sove the issue.

**Comment by ravingdragoon** [comment]
Seems to be fixed now. Thanks for the support! :)
