### ISSUE TITLE
Foundry V11 compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [boss-loot/Boss-Loot-Interactive-Magic-Items#5]
Can you please update this module to be compatible with Foundry-VTT V11?

**Comment by boss-loot** [comment]
Hello,

At present, our development focus is on updating the Patreon version of the module. This is a way for us to prioritize and recognize the contributions from the community that has supported this project financially, allowing us to continue development and introduce new items.

We anticipate that the Patreon version update will be completed within the next month. Following this, we fully intend to shift our focus to the GitHub module, ensuring all users can continue to enjoy and utilize our module.

Your patience and understanding during this transitional period are greatly appreciated.

Best regards

**Comment by boss-loot** [comment]
Boss Loot module it's now compatible with v11
Enjoy 😊
