### ISSUE TITLE
Token Shrinking

### ISSUE THREAD

**Issue by BlueWolfITA** [boss-loot/Boss-Loot-Interactive-Magic-Items#6]
Hello,
I've just recently installed your module. When using the vortex bow, after the effects have been applied the tokens who are effected are shrinked down no matter the size, how do i disable that or work around it?

**Comment by boss-loot** [comment]
Hello,

If the ability is used in combat, the effect automatically ends after one round and the tokens are resized to their normal size. There's nothing you need to do in this case, it should happen automatically.

If the ability is used outside of combat, you will need to manually remove the "Gravity Distortion Effect" from the affected tokens. Here's how you can do that:

1. Select the token affected by the effect.
2. Look for the "Effects" section in the token's character sheet.
3. Find "Gravity Distortion Effect" in the list and click the trash bin icon to remove it.
This should revert the tokens back to their original size.

Let me know if you have any more questions. 

Enjoy your gaming!
