### ISSUE TITLE
Stormforger attunement

### ISSUE THREAD

**Issue by CouncelofRhogars** [boss-loot/Boss-Loot-Interactive-Magic-Items#7]
It seems strange that cleric isnt apart of the list to attunement as there is an entire domain dedicated to storms and weather for clerics. It feels like they should be apart of this list as well.

**Comment by boss-loot** [comment]
If a cleric character has a backstory or a deity that aligns with the themes of storms, weather, or elemental forces, it could be very fitting for them to use the Stormforger.
You can update the item description and use it in your adventure.

Feel free to join our public Discord server where we have a dedicated channel for item discussions.

**Comment by boss-loot** [comment]
Item description can be updated.
