### ISSUE TITLE
Not PF1 Compatible

### ISSUE THREAD

**Issue by R0gu3P403n1x** [boss-loot/Boss-Loot-Interactive-Magic-Items#8]
Clearly not a bug, just unfortunately not compatible.  Can this be corrected?

**Comment by boss-loot** [comment]
At this moment the module it's not compatible with PF1 but we have an assets module that's system agnostic, maybe you can find some good use of it.
It is called **Boss Loot Animated FX Assets**.

**Comment by boss-loot** [comment]
Closed
